apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql17-gke-rk-auxxxx
  labels:
    app: mssql-auxxxx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-auxxxx
  template:
    metadata:
      labels:
        app: mssql-auxxxx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssql-auxxxx
        image: mcr.microsoft.com/mssql/server
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "F21swtdisp!!" 
        - name: MSSQL_DATA_DIR
          value: /var/opt/mssql/mdf
        - name: MSSQL_LOG_DIR
          value: /var/opt/mssql/ldf          
        volumeMounts:
        - name: mssql-base-volume
          mountPath: /var/opt/mssql
        - name: mssql-ldf-volume
          mountPath: /var/opt/mssql/ldf
        - name: mssql-mdf-volume
          mountPath: /var/opt/mssql/mdf
      volumes:
      - name: mssql-base-volume
        persistentVolumeClaim:
          claimName: mssql-base-volume
      - name: mssql-mdf-volume
        persistentVolumeClaim:
          claimName: mssql-mdf-volume
      - name: mssql-ldf-volume
        persistentVolumeClaim:
          claimName: mssql-ldf-volume
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-server-auxxx
spec:
  selector:
    app: mssql-auxxxx
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer